[package]
name = "hyprshell"
readme = "README.md"
documentation = "https://docs.rs/hyprshell"
version = "4.5.0"
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
exclude = [
    ".idea/*",
    ".github/*",
]

[dependencies]
anyhow.workspace = true
tracing.workspace = true
gtk.workspace = true
async-channel.workspace = true
clap = { version = "4.5.23", features = ["derive"] }
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter", "ansi"], default-features = false }
libc = { version = "0.2.172", default-features = false }

core-lib.workspace = true
exec-lib.workspace = true
windows-lib.workspace = true
launcher-lib.workspace = true

[features]
default = ["toml_config", "generate_config_command", "launcher_calc", "debug_command"]
toml_config = ["core-lib/toml_config"]
generate_config_command = ["core-lib/generate_config"]
launcher_calc = ["launcher-lib/calc", "core-lib/calc"]
debug_command = []
config_check_is_default = ["core-lib/no-default-config-values"]
bar = []

[workspace]
members = ["exec-lib", "core-lib", "windows-lib", "launcher-lib"]
resolver = "2"


[workspace.package]
version = "4.5.0"
description = "A modern GTK4-based window switcher and application launcher for Hyprland"
license = "MIT"
authors = ["h3rmt"]
keywords = ["hyprland"]
repository = "https://github.com/h3rmt/hyprshell/"
rust-version = "1.85.0"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0.98" }
tracing = { version = "0.1.41" }
serde_json = { version = "1.0.140" }
async-channel = { version = "2.3.1", default-features = true }
hyprland = { version = "0.4.0-beta.2", features = ["async-lite", "dispatch", "keyword", "data", "listener", "ctl", "config"], default-features = false }

gtk = { version = "0.9.6", package = "gtk4", default-features = false, features = ["v4_14"] }
gtk4-layer-shell = { version = "0.5.0" }

core-lib = { path = "core-lib", package = "hyprshell-core-lib", version = "=4.5.0" }
exec-lib = { path = "exec-lib", package = "hyprshell-exec-lib", version = "=4.5.0" }
windows-lib = { path = "windows-lib", package = "hyprshell-windows-lib", version = "=4.5.0" }
launcher-lib = { path = "launcher-lib", package = "hyprshell-launcher-lib", version = "=4.5.0" }

[profile.release]
strip = "debuginfo"
lto = true
opt-level = "s"
